name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

jobs:
    tests:
        runs-on: ubuntu-22.04

        name: "Sylius ${{ matrix.sylius }}, PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, ${{ matrix.database == 'mysql' && format('MySQL {0}', matrix.mysql) || matrix.database == 'postgres' && format('PostgreSQL {0}', matrix.postgres) }}, wkhtmltopdf: ${{ matrix.wkhtmltopdf }}, State Machine Adapter ${{ matrix.state_machine_adapter }}"

        strategy:
            fail-fast: false
            matrix:
                php: ["8.2", "8.3"]
                symfony: ["^6.4", "~7.3.0"]
                sylius: ["~2.0.0", "~2.1.0"]
                node: ["22.x"]
                database: ["mysql"]
                mysql: ["8.4"]
                wkhtmltopdf: ["0.12.6.1-2"]
                state_machine_adapter: ["symfony_workflow"]

                include:
                    -
                        php: "8.3"
                        symfony: "~7.3.0"
                        sylius: "~2.1.0"
                        node: "24.x"
                        database: "mysql"
                        mysql: "8.4"
                        wkhtmltopdf: "0.12.6.1-2"
                        state_machine_adapter: "winzou_state_machine"

                    -
                        php: "8.3"
                        symfony: "~7.2.0"
                        sylius: "~2.1.0"
                        node: "24.x"
                        database: "mysql"
                        mysql: "8.4"
                        wkhtmltopdf: false
                        state_machine_adapter: "symfony_workflow"

                    -
                        php: "8.3"
                        symfony: "~7.3.0"
                        sylius: "~2.1.0"
                        node: "24.x"
                        database: "postgres"
                        postgres: "15.8"
                        wkhtmltopdf: "0.12.6.1-2"
                        state_machine_adapter: "symfony_workflow"

        env:
            APP_ENV: test
            DATABASE_URL: ${{ matrix.database == 'mysql' && format('mysql://root:root@127.0.0.1/sylius?serverVersion={0}', matrix.mysql) || format('pgsql://postgres:postgres@127.0.0.1/sylius?serverVersion={0}', matrix.postgres) }}
            TEST_SYLIUS_STATE_MACHINE_ADAPTER: "${{ matrix.state_machine_adapter }}"

        steps:
            -
                uses: actions/checkout@v4

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: intl
                    tools: symfony
                    coverage: none

            -
                name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: "${{ matrix.node }}"

            -
                name: Shutdown default database services
                run: |
                      sudo service mysql stop || true
                      sudo service postgresql stop || true

            -
                name: Setup MySQL
                if: matrix.database == 'mysql'
                uses: mirromutth/mysql-action@v1.1
                with:
                      mysql version: "${{ matrix.mysql }}"
                      mysql root password: "root"

            -
                name: Setup PostgreSQL
                if: matrix.database == 'postgres'
                uses: harmon758/postgresql-action@v1
                with:
                    postgresql version: "${{ matrix.postgres }}"
                    postgresql password: "postgres"

            -
                name: Setup cache for wkhtmltopdf
                uses: actions/cache@v4
                id: cache-wkhtmltopdf
                if: matrix.wkhtmltopdf != false
                with:
                    path: /usr/local/bin/wkhtmltopdf
                    key: wkhtmltopdf-${{ matrix.wkhtmltopdf }}

            -
                name: Install wkthtmltopdf
                if: matrix.wkhtmltopdf != false && steps.cache-wkhtmltopdf.outputs.cache-hit != 'true'
                run: |
                    sudo apt-get install -y xfonts-base xfonts-75dpi
                    wget https://github.com/wkhtmltopdf/packaging/releases/download/${{ matrix.wkhtmltopdf }}/wkhtmltox_${{ matrix.wkhtmltopdf }}.jammy_amd64.deb
                    sudo dpkg -i wkhtmltox_${{ matrix.wkhtmltopdf }}.jammy_amd64.deb

            -
                name: Disable PDF generation
                if: matrix.wkhtmltopdf == false
                run: |
                    mv tests/TestApplication/etc/sylius_invoicing_pdf_generation_disabled.yaml tests/TestApplication/config/test

            -
                name: Get Composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -
                name: Cache Composer
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php }}-composer-

            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global config --no-plugins allow-plugins.symfony/flex true
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^1.10"
                    composer config extra.symfony.require "${{ matrix.symfony }}"

            -
                name: Restrict Sylius version
                if: matrix.sylius != ''
                run: composer require "sylius/sylius:${{ matrix.sylius }}" --no-update --no-scripts --no-interaction

            -
                name: Require Winzou State Machine
                if: "${{ matrix.state_machine_adapter == 'winzou_state_machine' }}"
                run: |
                  composer require winzou/state-machine:^0.4 --no-update   
                  composer require winzou/state-machine-bundle:^0.6 --no-update   

            -
                name: Install PHP dependencies
                run: composer install --no-interaction --no-scripts

            -
                name: Get Yarn cache directory
                id: yarn-cache
                run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

            -
                name: Cache Yarn
                uses: actions/cache@v4
                with:
                    path: ${{ steps.yarn-cache.outputs.dir }}
                    key: ${{ runner.os }}-node-${{ matrix.node }}-yarn-${{ hashFiles('**/package.json **/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-node-${{ matrix.node }}-yarn-

            -
                name: Install JS dependencies
                run: (cd vendor/sylius/test-application && yarn install)

            -
                name: Prepare test application database
                run: |
                    vendor/bin/console doctrine:database:create -vvv
                    vendor/bin/console doctrine:migrations:migrate -n -vvv -q

            -
                name: Prepare test application assets
                run: |
                    vendor/bin/console assets:install public -vvv
                    (cd vendor/sylius/test-application && yarn build:prod)

            -
                name: Prepare test application cache
                run: vendor/bin/console cache:warmup -vvv

            -
                name: Load fixtures in test application
                run: vendor/bin/console sylius:fixtures:load -n

            -
                name: Run security check
                run: symfony security:check

            -
                name: Run analysis
                run: composer analyse

            -
                name: Run PHPSpec
                run: vendor/bin/phpspec run --ansi -f progress --no-interaction

            -
                name: Run PHPUnit
                run: vendor/bin/phpunit --colors=always

            -
                name: Run Behat
                run: |
                    if [ "${{ matrix.wkhtmltopdf }}" != "false" ]; then
                        vendor/bin/behat --colors --strict -vvv --no-interaction -f progress --tags="~@pdf_disabled" || vendor/bin/behat --colors --strict -vvv --no-interaction -f progress --rerun;
                    else
                        vendor/bin/behat --colors --strict -vvv --no-interaction -f progress --tags="~@pdf_enabled" || vendor/bin/behat --colors --strict -vvv --no-interaction -f progress --rerun;
                    fi

            -
                name: Upload Behat logs
                uses: actions/upload-artifact@v4
                if: failure()
                with:
                    name: Behat logs
                    path: etc/build/
                    if-no-files-found: ignore
